name: 'telliot-feeds mkdocs'

on:
  push:
    branches:
      - dev #Todo: change this to main; once we have stable version

permissions:
  contents: write

env:
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  mkdocs:
    name: 'Publish Documentation'
    runs-on: ubuntu-latest
    env:
      working-directory: ${{ github.workspace }}/iac

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Obtain Cache ID
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install mkdocs
        run: |
          pip install mkdocs-material mkdocstrings mkdocs-autorefs

      - name: Deploy Documentation
        run: mkdocs gh-deploy --force